Enable fft prims via fallback to CPU manually
intel/torch-xpu-ops pull request #147
Opened 2024-04-17 02:20 UTC by ZhiweiYan-96

Enable fft prims via fallback to CPU manually

2024-04-18 06:13 UTC, EikanWang requested changes
Please fix the UT failures.

2024-04-22 08:40 UTC, fengyuan14 commented on src/aten/SpectralOps.cpp
> +  return out.copy_(out_cpu);
What's the return ?

2024-05-01 13:30 UTC, EikanWang approved these changes

2024-05-14 06:18 UTC, xytintel commented
Close PR since cpu fallback already includes in [code-link](https://github.com/intel/torch-xpu-ops/blob/main/src/aten/XPUFallback.template#L232C5-L234C16).

2024-05-14 06:18 UTC, closed without merging