Add sigmoid fwd & bwd ops and kernels
intel/torch-xpu-ops pull request #218
Opened 2024-05-14 08:49 UTC by AlienLiang23

2024-05-14 08:52 UTC, AlienLiang23 commented
![image](https://github.com/intel/torch-xpu-ops/assets/51150101/e6565615-3373-404a-a01c-5823ce958215)
all cases passed except **TestCommonXPU.test_out_warning_nn_functional_logsigmoid_xpu** which is already in the skip list

2024-05-15 09:01 UTC, xytintel approved these changes

2024-05-15 11:19 UTC, fengyuan14 commented on src/aten/sycl/BinaryKernels.cpp
> +struct SigmoidBackwardFunctor2 {
Please give meaningful naming.

2024-05-15 11:20 UTC, fengyuan14 commented on src/aten/sycl/BinaryKernels.cpp
> +struct SigmoidBackwardFunctor2 {
Like `SigmoidBackwardFloatingFunctor`

2024-05-15 11:20 UTC, fengyuan14 commented on src/aten/sycl/BinaryKernels.cpp
> +struct SigmoidBackwardFunctor {
Please give meaningful naming.

2024-05-15 11:23 UTC, fengyuan14 commented on src/aten/sycl/BinaryKernels.cpp
> +template <typename scalar_t>
Please move the change to corresponding file as stock CUDA, It should be `aten/src/ATen/native/cuda/BinaryMiscBackwardOpsKernels.cu`?

2024-05-24 22:36 UTC, dvrogozh requested changes

2024-05-24 22:36 UTC, dvrogozh commented on src/aten/sycl/BinaryKernels.cpp
> +        "sigmoid_backward_cuda",
typo?
```suggestion
        "sigmoid_backward_xpu",
```

2024-06-03 02:51 UTC, fengyuan14 commented on src/aten/sycl/BinaryKernels.cpp
> +        "sigmoid_backward_cuda",
Fixed by the file refactor.

2024-06-04 00:46 UTC, merged