Update pin_memory implementation follow stock pytorch change
intel/torch-xpu-ops pull request #639
Opened 2024-07-23 10:50 UTC by majing921201

pin_memory API, implementation and test case changed in stock pytorch

2024-07-23 14:38 UTC, dvrogozh requested changes
Emm... Update and delete implementation are different things :). Can you, please, explain (in PR description) why implementation is not needed anymore on torch-xpu-ops side? Also, did you check that https://github.com/pytorch/pytorch/issues/126491 continues to work?

2024-07-24 00:14 UTC, fengyuan14 commented
> Emm... Update and delete implementation are different things :). Can you, please, explain (in PR description) why implementation is not needed anymore on torch-xpu-ops side? Also, did you check that [pytorch/pytorch#126491](https://github.com/pytorch/pytorch/issues/126491) continues to work?

Make sense. We will add comments. Please see the latest description.

2024-07-24 00:18 UTC, fengyuan14 approved these changes

2024-07-24 00:18 UTC, merged

2024-07-24 00:21 UTC, dvrogozh commented
Thank you for updating description. Looks good to me.