Add aten::log_normal_
intel/torch-xpu-ops pull request #766
Opened 2024-08-15 07:03 UTC by hjhee

- log_normal_

2024-08-26 06:34 UTC, majing921201 commented on src/ATen/native/xpu/sycl/DistributionLogNormalKernel.cpp
> +#include <ATen/AccumulateType.h>
remove no need to include head file

2024-08-26 06:37 UTC, majing921201 commented on src/ATen/native/xpu/sycl/DistributionLogNormalKernel.cpp
> +#include <ATen/native/xpu/sycl/DistributionTemplates.h>
remove

2024-08-26 06:37 UTC, majing921201 commented on src/ATen/native/xpu/sycl/DistributionLogNormalKernel.cpp
> +#include <comm/Runtime.h>
remove, please check above head files are used ?

2024-08-26 06:45 UTC, majing921201 commented
add 'log_normal' to test list

2024-10-14 06:12 UTC, xytintel requested changes

2024-10-14 06:12 UTC, xytintel commented on src/ATen/native/xpu/sycl/DistributionTemplates.h
> +      "log_normal__xpu_",
log_normal_xpu

2024-10-14 06:12 UTC, xytintel commented on src/ATen/native/xpu/sycl/DistributionTemplates.h
> +        uniform_and_transform<scalar_t, accscalar_t, rand4_engine_calls>(
You should use `normal_and_transform` as CUDA does

2024-10-16 08:17 UTC, xytintel commented
![image](https://github.com/user-attachments/assets/6001a7a4-8d20-48b0-bfae-9e8224a4599c)
![image](https://github.com/user-attachments/assets/505ccde7-3913-4015-8d6e-69d39a21bd3d)

2024-10-16 08:20 UTC, xytintel approved these changes

2024-10-17 11:02 UTC, merged