Add aten::_ctc_loss and its variants
intel/torch-xpu-ops pull request #925
Opened 2024-09-19 08:23 UTC by xytintel

- [ ] _ctc_loss
- [ ] _ctc_loss.Tensor
- [ ]  _ctc_loss_backward
- [ ] _ctc_loss_backward.Tensor

2024-09-19 15:39 UTC, dvrogozh requested changes
ops should be excluded from here:
https://github.com/intel/torch-xpu-ops/blob/c13499159c2a8d7b8f67342674422b165b24684f/src/ATen/native/xpu/XPUFallback.template#L169-L170
and added to
https://github.com/intel/torch-xpu-ops/blob/main/yaml/xpu_functions.yaml

2024-09-29 03:02 UTC, fengyuan14 commented on src/ATen/native/xpu/sycl/LossCTCKernels.cpp
> +  // and reusing) from SoftMax.cu...
The comments here do seem CUDA related. Please correct and elaborate the comments from Intel GPU perspective.

2024-09-29 03:04 UTC, fengyuan14 commented on src/ATen/native/xpu/sycl/LossCTCKernels.cpp
> +      ? 1024
Which is not device compatible, if simd16 and LGRF are enabled on PVC or SIMD8 is enabled on MTL, please use runtime query.

2024-09-29 03:12 UTC, fengyuan14 commented on src/ATen/native/xpu/sycl/LossCTCKernels.cpp
> +      ? 1024
Ditto.

2024-10-12 03:07 UTC, xytintel commented
![image](https://github.com/user-attachments/assets/0698b54c-04fb-4e0d-a101-71e6e9f5025a)
![image](https://github.com/user-attachments/assets/c4c585de-d677-4422-b073-70386988aa5a)

2024-10-12 07:19 UTC, ZhiweiYan-96 approved these changes

2024-10-13 03:34 UTC, merged